### PR TITLE
LPS-53184

### PR DESCRIPTION
**Pull request by topolik**

### CODE REVIEW

**Comment by samuelkong** [comment]
Thanks. Sent to Brian. https://github.com/brianchandotcom/liferay-plugins/pull/4201

**Comment by amosfong** [comment]
Just curious, why does it need to be escaped twice?

**Comment by samuelkong** [comment]
@amosfong 

Because there's two page's in play here. The first page is the `view.jsp` and the second is the Google Maps info window.

The first `HtmlUtil.escapeJS` is for the view.jsp since we're in a JavaScript block.

The Google Maps info window takes HTML content so we need to escape the content before it's given to the info window. So the second `HtmlUtil.escape` is to escape the content for the info window.

Without the second `HtmlUtil.escape`, you'll have potentially vulnerable HTML code in the info window. And you can't remove the first `HtmlUtil.escapeJS` because you need to escape more when you're in a JavaScript block then when you're in HTML so `HtmlUtil.escape` is not sufficient for the JavaScript block in view.jsp.

**Comment by topolik** [comment]
Whops, I see Sam already answered :)

But because it took me some time I also answer, if you don't mind :)

Short answer
----
We have 2 parsers decoding the value, each of them with different decoding routine.

Both will write `` into doc:
```<script>document.write('<%= HtmlUtil.escape("\\x3cimg\\x3e") %>')</script> ```
```<script>document.write('<%= HtmlUtil.escapeJS("") %>')</script> ```

Long answer
----
JS parser decodes different things then HTML parser.

Here we are in a `<script>` tag so it goes directly into JS parser. And then JS will later write the text as HTML inside the bubble/popup, which will be parsed again with HTML parser.

We could write the sequence as HTML.parse(JS.parse(sentence))

So we have two parsers we are sure will decode the vector. Therefore we should prepare the vector for each decoding so that the string doesn't lose the original meaning when decoded and parsed by each of the parser.

So first we encode it for JS and then for HTML: HtmlUtil.escapeJS(HtmlUtil.escapeHTML(vector))

During decoding then we have: HTML.parse(JS.parse(HtmlUtil.escapeJS(HtmlUtil.escapeHTML(vector))))

Because:
- `X == HTML.parse(HtmlUtil.escape(X))`
- `Y == JS.parse(HtmlUtil.escapeJS(Y))`
- `HtmlUtil.escape(vector) ==  JS.parse(HtmlUtil.escapeJS(HtmlUtil.escape(vector)))`
- `HTML.parse(HtmlUtil.escape(vector)) == HTML.parse(JS.parse(HtmlUtil.escapeJS(HtmlUtil.escape(vector))))`
- `vector == HTML.parse(HtmlUtil.escape(vector)) == HTML.parse(JS.parse(HtmlUtil.escapeJS(HtmlUtil.escape(vector))))`

If we omit one escaping, the meaning can be desctructed by one of JS/HTML parsers, as follows:

HTML.parse(JS.parse(HtmlUtil.escapeJS(~~HtmlUtil.escape~~(vector))))
`== HTML.parse(JS.parse(HtmlUtil.escapeJS((vector))))`
`== HTML.parse((vector))`
-> Here we have direct XSS
-> We can just write HTML inside the vector and it will be executed

HTML.parse(JS.parse(~~HtmlUtil.escapeJS~~(HtmlUtil.escape(vector))))
`== HTML.parse(JS.parse((HtmlUtil.escape(vector))))`
-> Here is situation more complex because our `HtmlUtil.escape` encodes also apostrophes and quotes, which is not needed for HTML parser, but we do.
-> But because in this special case we are inside JS string, we can use JS string escaping using backslash, which is not touched by HtmlUtil.escape
-> So having vector `\x3cimg\x3e`
`== HTML.parse(JS.parse((HtmlUtil.escape('\x3cimg\x3e'))))`
`== HTML.parse(JS.parse(('\x3cimg\x3e')))`
`== HTML.parse('')`

**Comment by topolik** [comment]
The situation can be more complex, for example in `<a onclick="document.write(...)">` it goes first to HTML parser to parse the attribute, and then to JS and HTML, so we need 3 encodings here.

And even more complex - `<a href="javascript:document.write(...)">` with four encodings:
 - HTML parser ... attribute
 - URL parser ... inside HREF
 - JS parser ... `javascript:` URI
 - HTML parser ... `document.write()`

**Comment by amosfong** [comment]
got it, thanks for the in depth explanations =)

**Pull request closed without merging**
